version: 2

sources:
  - name: brazil_ecommerce
    database: rinniedsai
    tables:
      - name: olist_customers_dataset
      - name: olist_geolocation_dataset_cleaned
      - name: olist_order_items_dataset_cleaned
      - name: olist_order_payments_dataset_cleaned
      - name: olist_order_reviews_dataset_cleaned
      - name: olist_orders_dataset_cleaned
      - name: olist_products_dataset
      - name: olist_sellers_dataset
      - name: product_category_name_translation
